# Generated by Django 4.2.2 on 2023-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='contract',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ifcs',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
